import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import { ArrowLeft, Check, Copy, ExternalLink, FileText, Globe, Plus, Search, Star, Trash2, WandSparkles } from 'lucide-react';
import { VALID_CATEGORIES } from '../data/blogPosts';
import { deleteManagedPost, getManagedPosts, saveManagedPost } from '../utils/blogStore';

const emptyPost = { id: '', title: '', slug: '', metaTitle: '', metaDescription: '', excerpt: '', category: 'Software Guide', tags: '', keywords: '', targetMarket: 'Global', image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&h=630&fit=crop', imageAlt: '', readTime: '5 min read', content: '', status: 'draft', featured: false, socialCaption: '', hashtags: '', ctaText: 'Start the free trial', ctaUrl: '/login' };
const toForm = post => ({ ...emptyPost, ...post, tags: (post.tags || []).join(', '), keywords: (post.keywords || []).join(', '), targetMarket: (post.targetMarket || ['Global']).join(', ') });
const fromForm = form => ({ ...form, tags: form.tags.split(',').map(x => x.trim()).filter(Boolean), keywords: form.keywords.split(',').map(x => x.trim()).filter(Boolean), targetMarket: form.targetMarket.split(',').map(x => x.trim()).filter(Boolean), date: form.date || new Date().toISOString().slice(0, 10) });

export default function BlogStudioPage() {
  const [posts, setPosts] = useState(getManagedPosts);
  const [selected, setSelected] = useState(null);
  const [status, setStatus] = useState('all');
  const [query, setQuery] = useState('');
  const [form, setForm] = useState(emptyPost);
  const visible = useMemo(() => posts.filter(post => (status === 'all' || post.status === status) && post.title.toLowerCase().includes(query.toLowerCase())), [posts, status, query]);
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const edit = post => { setSelected(post.id); setForm(toForm(post)); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const startNew = () => { setSelected(null); setForm(emptyPost); };
  const save = nextStatus => {
    if (!form.title.trim() || !form.slug.trim() || !form.metaDescription.trim() || !form.content.trim()) return toast.error('Add a title, slug, meta description, and article content.');
    if (form.metaDescription.length < 80 || form.metaDescription.length > 160) return toast.error('Meta description should be 80–160 characters.');
    const duplicate = posts.some(post => post.slug === form.slug.trim() && post.id !== form.id);
    if (duplicate) return toast.error('That slug is already in use.');
    const saved = saveManagedPost({ ...fromForm({ ...form, status: nextStatus }), id: form.id || selected });
    setPosts(getManagedPosts()); setForm(toForm(saved)); setSelected(saved.id); toast.success(nextStatus === 'published' ? 'Article published.' : 'Draft saved.');
  };
  const remove = post => { if (!window.confirm(`Delete “${post.title}”?`)) return; deleteManagedPost(post.id); setPosts(getManagedPosts()); if (selected === post.id) startNew(); toast.success('Article deleted.'); };
  const duplicate = post => { const copy = { ...post, id: '', slug: `${post.slug}-copy`, title: `${post.title} — Copy`, status: 'draft', featured: false }; setForm(toForm(copy)); setSelected(null); toast.success('Copy ready to edit.'); };
  const copyUrl = async () => { await navigator.clipboard.writeText(`${window.location.origin}/blog/${form.slug}`); toast.success('Share URL copied.'); };

  return <div className="min-h-screen bg-slate-950 text-slate-100">
    <header className="border-b border-slate-800 bg-slate-950/95 sticky top-0 z-20"><div className="max-w-7xl mx-auto px-5 py-4 flex items-center justify-between gap-4"><div className="flex items-center gap-3"><Link to="/admin" className="p-2 rounded-lg hover:bg-slate-800" aria-label="Back to admin"><ArrowLeft size={18} /></Link><div><p className="text-xs uppercase tracking-[0.2em] text-cyan-400 font-bold">BillByteKOT</p><h1 className="text-xl font-bold">Blog Studio</h1></div></div><button onClick={startNew} data-testid="new-post" className="inline-flex items-center gap-2 rounded-lg bg-cyan-400 text-slate-950 px-4 py-2 font-bold hover:bg-cyan-300"><Plus size={17} /> New article</button></div></header>
    <main className="max-w-7xl mx-auto px-5 py-8 grid lg:grid-cols-[280px_1fr] gap-6">
      <aside className="space-y-4"><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="flex items-center gap-2 text-sm font-bold mb-3"><FileText size={16} className="text-cyan-400" /> Publishing queue</div>{['all', 'published', 'draft', 'scheduled'].map(item => <button key={item} onClick={() => setStatus(item)} className={`w-full text-left px-3 py-2 rounded-lg text-sm capitalize ${status === item ? 'bg-slate-700 text-cyan-300' : 'text-slate-400 hover:bg-slate-800'}`}>{item}<span className="float-right">{item === 'all' ? posts.length : posts.filter(post => post.status === item).length}</span></button>)}</div><div className="relative"><Search size={16} className="absolute left-3 top-3 text-slate-500" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Find an article" className="w-full rounded-lg border border-slate-800 bg-slate-900 pl-9 pr-3 py-2.5 text-sm outline-none focus:border-cyan-400" /></div><div className="rounded-xl border border-slate-800 bg-slate-900 p-4 text-sm text-slate-400"><WandSparkles size={18} className="text-amber-300 mb-2" /><p className="text-slate-200 font-semibold">Reach-ready content</p><p className="mt-1 leading-6">Use one clear keyword, one useful promise, and one trial CTA per article. Share the social caption after publishing.</p></div>{visible.map(post => <button key={post.id} onClick={() => edit(post)} className={`w-full text-left rounded-xl border p-3 ${selected === post.id ? 'border-cyan-400 bg-slate-800' : 'border-slate-800 bg-slate-900 hover:border-slate-600'}`}><div className="flex justify-between gap-2"><span className="font-semibold text-sm line-clamp-2">{post.title}</span>{post.featured && <Star size={14} className="text-amber-300 shrink-0" />}</div><span className="text-xs text-slate-500 capitalize">{post.status} · {post.category}</span></button>)}</aside>
      <section className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5 md:p-7"><div className="flex items-start justify-between gap-4 mb-6"><div><p className="text-xs uppercase tracking-[0.18em] text-slate-500">{selected ? 'Editing article' : 'New article'}</p><h2 className="text-2xl font-bold mt-1">{form.title || 'Untitled article'}</h2></div>{form.slug && <div className="flex gap-2"><button onClick={copyUrl} className="p-2 rounded-lg border border-slate-700 hover:border-cyan-400" title="Copy share URL"><Copy size={16} /></button><a href={`/blog/${form.slug}`} target="_blank" rel="noreferrer" className="p-2 rounded-lg border border-slate-700 hover:border-cyan-400" title="Preview article"><ExternalLink size={16} /></a></div>}</div>
        <div className="grid md:grid-cols-2 gap-4">{[['title','Title'],['slug','Slug'],['metaTitle','SEO title'],['metaDescription','Meta description'],['excerpt','Excerpt'],['image','Image URL'],['imageAlt','Image alt text'],['readTime','Read time'],['tags','Tags (comma separated)'],['keywords','Keywords (comma separated)'],['targetMarket','Target markets (comma separated)'],['socialCaption','Social caption'],['hashtags','Hashtags'],['ctaText','CTA label'],['ctaUrl','CTA URL']].map(([key,label]) => <label key={key} className={key === 'metaDescription' || key === 'excerpt' || key === 'socialCaption' ? 'md:col-span-2 text-sm text-slate-400' : 'text-sm text-slate-400'}>{label}<input data-testid={`field-${key}`} value={form[key] || ''} onChange={event => update(key, event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-slate-100 outline-none focus:border-cyan-400" /></label>)}</div>
        <div className="grid md:grid-cols-3 gap-4 mt-4"><label className="text-sm text-slate-400">Category<select value={form.category} onChange={event => update('category', event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5"><option>{VALID_CATEGORIES.join('</option><option>')}</option></select></label><label className="text-sm text-slate-400">Status<select value={form.status} onChange={event => update('status', event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5"><option value="draft">Draft</option><option value="published">Published</option><option value="scheduled">Scheduled</option></select></label><label className="flex items-center gap-2 mt-7 text-sm text-slate-300"><input type="checkbox" checked={form.featured} onChange={event => update('featured', event.target.checked)} /> Feature on blog</label></div>
        <label className="block text-sm text-slate-400 mt-5">Article content <textarea data-testid="field-content" value={form.content} onChange={event => update('content', event.target.value)} rows={18} placeholder="Write in Markdown…" className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-3 text-slate-100 font-mono text-sm leading-6 outline-none focus:border-cyan-400" /></label>
        <div className="mt-5 rounded-xl border border-slate-800 bg-slate-950 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><Globe size={16} className="text-cyan-400" /> Search preview</div><p className="text-cyan-300 mt-3 font-semibold truncate">{form.metaTitle || form.title || 'Your SEO title'}</p><p className="text-xs text-slate-500 mt-1">billbytekot.in/blog/{form.slug || 'your-slug'}</p><p className="text-sm text-slate-400 mt-1 line-clamp-2">{form.metaDescription || 'A clear description helps people choose your article from search results.'}</p></div>
        <div className="flex flex-wrap gap-3 mt-6"><button onClick={() => save('draft')} data-testid="save-draft" className="rounded-lg border border-slate-700 px-4 py-2.5 font-semibold hover:border-cyan-400">Save draft</button><button onClick={() => save(form.status === 'scheduled' ? 'scheduled' : 'published')} data-testid="publish-post" className="inline-flex items-center gap-2 rounded-lg bg-cyan-400 text-slate-950 px-5 py-2.5 font-bold hover:bg-cyan-300"><Check size={17} /> {form.status === 'scheduled' ? 'Save schedule' : 'Publish'}</button>{selected && <><button onClick={() => duplicate(posts.find(post => post.id === selected))} className="rounded-lg border border-slate-700 px-4 py-2.5 hover:border-cyan-400">Duplicate</button><button onClick={() => remove(posts.find(post => post.id === selected))} className="inline-flex items-center gap-2 rounded-lg border border-red-900 text-red-300 px-4 py-2.5 hover:bg-red-950"><Trash2 size={16} /> Delete</button></>}</div></section>
    </main>
  </div>;
}
